DROP TABLE IF EXISTS CRASH;
DROP TABLE IF EXISTS LEVEL;
DROP TABLE IF EXISTS SISTEMA;
DROP TABLE IF EXISTS PERMISSAO;
DROP TABLE IF EXISTS USUARIO;



CREATE TABLE LEVEL
(
  LEV_ID INT IDENTITY PRIMARY KEY,
  LEV_DESCRICAO VARCHAR(250) NOT NULL
);

INSERT INTO LEVEL
  (LEV_DESCRICAO)
VALUES
  ('Trace'),
  ('Debug'),
  ('Info'),
  ('Warn'),
  ('Error'),
  ('Fatal');

CREATE TABLE SISTEMA
(
  SIS_ID INT IDENTITY PRIMARY KEY,
  SIS_DESCRICAO VARCHAR(250) NOT NULL,
  SIS_STATUS VARCHAR(1) NOT NULL
);

INSERT INTO SISTEMA
  (SIS_DESCRICAO, SIS_STATUS)
VALUES
  ('ERP-NEGÓCIO', 'A'),
  ('APP-NEGÓCIO', 'A');

CREATE TABLE CRASH
(
  CRA_ID INT IDENTITY PRIMARY KEY,
  LEV_ID INT NOT NULL,
  CRA_DESCRICAO_EVENTO VARCHAR(250) NOT NULL,
  CRA_LOG VARCHAR(250) NOT NULL,
  SIS_ID INT NOT NULL,
  CRA_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CRA_QUANTIDADE INT NOT NULL
);

ALTER TABLE CRASH
    ADD FOREIGN KEY (LEV_ID) 
    REFERENCES LEVEL(LEV_ID);

ALTER TABLE CRASH
    ADD FOREIGN KEY (SIS_ID) 
    REFERENCES SISTEMA(SIS_ID);

INSERT INTO CRASH
  (LEV_ID, CRA_DESCRICAO_EVENTO, CRA_LOG, SIS_ID, CRA_DATA, CRA_QUANTIDADE)
VALUES
  (5, 'Inserir', 'INSERT has more expressions than target columns', 1, CURRENT_TIMESTAMP
(), 1);



CREATE TABLE USUARIO
(
  USE_ID INT IDENTITY PRIMARY KEY,
  USE_NOMECOMPLETO VARCHAR(50) NOT NULL,
  USE_EMAIL VARCHAR(50) NOT NULL,
  USE_PASSWORD VARCHAR(150) NOT NULL,
  USE_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USUARIO
  (USE_NOMECOMPLETO, USE_EMAIL, USE_PASSWORD, USE_DATA)
VALUES
  ('IVAIR PUERARI', 'puerariivair@gmail.com', '$2y$12$35PKUjUXynd4ibhZOM4m1.7errlJv/Z/7IUUNHsy9iMfD8kSIl462', CURRENT_TIMESTAMP
());

INSERT INTO USUARIO
  (USE_NOMECOMPLETO, USE_EMAIL, USE_PASSWORD, USE_DATA)
VALUES
  ('CODENATION', 'codenation@codenation.com', '$2y$12$kttfQuwsXj5i6TNZEFq7zu0j/dE8JSHDPgvsdxKp1abIoK90eWDcy', CURRENT_TIMESTAMP
());

CREATE TABLE PERMISSAO
(
  PER_ID INT IDENTITY PRIMARY KEY,
  USE_ID INT NOT NULL,
  PER_VALOR VARCHAR(50) NOT NULL
);

ALTER TABLE PERMISSAO
    ADD FOREIGN KEY (USE_ID) 
    REFERENCES USUARIO(USE_ID);

INSERT INTO PERMISSAO
  (USE_ID, PER_VALOR)
VALUES
  (1, 'USER'),
  (2, 'ADMIN');

 